package data;
// Generated Jul 22, 2017 9:57:20 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Ureq generated by hbm2java
 */
public class Ureq  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private String place;
     private Date time;
     private String number;
     private String name;
     private String bgroup;
     private String city;

    public Ureq() {
    }

	
    public Ureq(int uid) {
        this.uid = uid;
    }
    public Ureq(int uid, String place, Date time, String number, String name, String bgroup, String city) {
       this.uid = uid;
       this.place = place;
       this.time = time;
       this.number = number;
       this.name = name;
       this.bgroup = bgroup;
       this.city = city;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBgroup() {
        return this.bgroup;
    }
    
    public void setBgroup(String bgroup) {
        this.bgroup = bgroup;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


