package data;
// Generated Jul 22, 2017 9:57:20 PM by Hibernate Tools 3.6.0



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String sex;
     private int age;
     private String address;
     private String city;
     private String state;
     private String country;
     private String pin;
     private String email;
     private String phone;
     private String blood;
     private String donate;
     private String accept;
     private String password;

    public Users() {
    }

	
    public Users(String firstName, String sex, int age, String address, String city, String state, String country, String pin, String email, String phone, String blood, String password) {
        this.firstName = firstName;
        this.sex = sex;
        this.age = age;
        this.address = address;
        this.city = city;
        this.state = state;
        this.country = country;
        this.pin = pin;
        this.email = email;
        this.phone = phone;
        this.blood = blood;
        this.password = password;
    }
    public Users(String firstName, String lastName, String sex, int age, String address, String city, String state, String country, String pin, String email, String phone, String blood, String donate, String accept, String password) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.sex = sex;
       this.age = age;
       this.address = address;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pin = pin;
       this.email = email;
       this.phone = phone;
       this.blood = blood;
       this.donate = donate;
       this.accept = accept;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getBlood() {
        return this.blood;
    }
    
    public void setBlood(String blood) {
        this.blood = blood;
    }
    public String getDonate() {
        return this.donate;
    }
    
    public void setDonate(String donate) {
        this.donate = donate;
    }
    public String getAccept() {
        return this.accept;
    }
    
    public void setAccept(String accept) {
        this.accept = accept;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


